name: TypeScript Container Action TEST
description: Template to create a GitHub container action in Node.js with TypeScript
branding:
  icon: book-open
  color: blue
inputs:
  name:
    required: true
    description: Name to greet
runs:
  using: docker
  image: Dockerfile
