name: AlgoSec_Client_CI/CD
on:
  pull_request:
    branches:
      - "main"
jobs:
  # AlgosecRiskAnalysisWorkflow:
  #   uses: algosec/risk-analysis-workflow/.github/workflows/release.yml@main
  #   secrets:
  #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
  #     TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  # debug:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: hmarr/debug-action@v2
  algosec-risk-analysis-probot-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#   algosec-risk-analysis-action:
#      runs-on: ubuntu-latest
#      steps:
#       - uses: algosec/risk-analysis-action-github@v0.0.6
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
